### PR TITLE
Logout page

### PR DESCRIPTION
**Pull request by AswathyVNair**

### CODE REVIEW

**Review by zoef-yt — APPROVED** [review]
Small code good to merge. Please be sure to add a description to your pr.

**Review by srishtigautam21 — APPROVED** [review]
good to merge

**Review by VishnuVNairCodes — APPROVED** [review]
Neat concise code. Good to merge.

**Review by sudipkundu999 — APPROVED** [review]
Clean code. Easy to understand.
Make sure to add a description to your PR from next time 
(a screenshot/ preview link to the exact page)

**Pull request merged**
